version: "3.9"

services:
  eurekaserver:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: skumar97/eurekaserver:v3
    container_name: eurekaserver
    networks:
      - my-network

    ports:
      - "8761:8761"

  apigateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: skumar97/apigateway:v3
    container_name: apigateway
    networks:
      - my-network
    depends_on:
      - eurekaserver
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - spring.profiles.active=docker

  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    image: skumar97/app1:v3
    container_name: app1
    networks:
      - my-network
    depends_on:
      - apigateway
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - APP2_HOSTNAME=http://app2:8082

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    image: skumar97/app2:v3
    container_name: app2
    networks:
      - my-network
    depends_on:
      - apigateway
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - APP1_HOSTNAME=http://app1:8081

networks:
  my-network:
    driver: bridge